### ISSUE TITLE
Installer stops responding when downloading Wyrmstooth 

### ISSUE THREAD

**Issue by MattLish** [RingComics/azuras-star#12]
**Bug**

**What it should do:** Continue to respond while downloading all the resources
**What it currently does:** Shows as not responding, even if it's still downloading

**Description**:

When downloading all the preinstall packages, the installer can often stop responding (even if leaving it long enough causes it to come back)

It looks like it's actually working in the background (I can see mods continuing to be downloaded) but I cannot interact with the window and it not responding might cause a user to close it.

**Comment by MattLish** [comment]
Seems to stop responding when downloading Wyrmstooth 1.17B, likely because it's quite large.

Maybe this also needs to be a manual download?

Or a way to tell PS to do this in the background so the automaton download can begin.

**Comment by RingComics** [comment]
I do believe there is a way to run downloads in the background, and we can add a progress bar to the form to give the user some feedback as I mentioned in #11. The only reason DynDOLOD is a manual file is its not hosted on the nexus, its hosted on Mega which pretty aggressively stops bot downloads. I don't know about letting automaton run while still downloading the files, people with slow internet will perish.

**Comment by RingComics** [comment]
Running through a test with the new code you implemented, and there is a progress window that pops up. This only happens when running the compiled EXE.
[Here](https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5) is the script I use to compile the code into an EXE, if you want to download it for your own testing. Since this problem only exists in a dev environment and not a user experience, I'm closing out this issue. Thanks!

**Comment by MattLish** [comment]
Oh, that's good! I haven't actually run the .exe before, ha
